---
# tasks file for fav-packages
- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest

- name: Update all packges to the latest version
  apt:
    upgrade: dist

- name: Install favorite packages
  apt:
    pkg: "{{ packages }}"
    state: present

- name: Change hostname
  hostname:
    name: "{{ new_hostname }}"

- name: Ensure docker config file exists (or create)
  copy:
    content: ""
    dest: /etc/nologin
    force: false
    group: sys
    owner: root
    mode: 0555

#- name: Ping
#  ansible.builtin.ping:
