---

# tasks file for fav-packages

- name: Upgrade all packages to the latest version
  ansible.builtin.apt:
    name: "*"
    state: latest

- name: Upgrade all packages using dist upgrade
  ansible.builtin.apt:
    upgrade: dist

- name: Install favorite packages
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present

- name: Install sysstat
  ansible.builtin.apt:
    name: sysstat
    state: present
    update_cache: true

- name: Enable sysstat collection
  ansible.builtin.lineinfile:
    path: /etc/default/sysstat
    regexp: '^ENABLED='
    line: 'ENABLED="true"'

- name: Enable and start sysstat
  ansible.builtin.systemd:
    name: sysstat
    enabled: true
    state: started
    daemon_reload: true

# - name: Change hostname
#   ansible.builtin.hostname:
#     name: "{{ new_hostname }}"

# - name: Ensure docker config file exists (or create)
#   ansible.builtin.copy:
#     content: ""
#     dest: /etc/nologin
#     force: false
#     group: sys
#     owner: root
#     mode: "0555"

# - name: Ping
#   ansible.builtin.ping:
